### ISSUE TITLE
SDK show BOX WITHOUT LABEL

### ISSUE THREAD

**Issue by taghouti-ghofrane** [heartexlabs/label-studio-sdk#102]
hello 
i was trying to send annotations from model prediction to label studio using sdk 

i formatted the x , y , width and height , and all is fine .

i just have this problem , the box shows without label .
![image](https://user-images.githubusercontent.com/45640918/214589224-325c8c8b-cbeb-47af-b2cf-e9fc2a023181.png)
The code used is : 

```
results_pre=[]
results_pre.append({
                "from_name": "tag",
                "to_name": "image",
                'type': 'rectanglelabels',
                'value': {
                    'rectanglelabels': ['Table'],
                    'x': x_c ,
                    'y':y_c,
                    'width':wid_c,
                    'height': high_c,
                    
                    }})

task_ids = project.get_tasks_ids()
project.create_prediction(task_id=task_ids[11], model_version='model_9', result = results_pre , score=0.5)
```

**Comment by taghouti-ghofrane** [comment]
yes 
![image](https://user-images.githubusercontent.com/45640918/214594772-10043423-669f-4b1d-a98c-a2d9760bd9a0.png)

**Comment by taghouti-ghofrane** [comment]
that confused me even in this example it works https://github.com/heartexlabs/label-studio-sdk/blob/master/examples/import_preannotations/import_brush_predictions.py

also i tried it yesterday it works

**Comment by makseq** [comment]
```
"from_name": "tag",
```
=>
```
"from_name": "label",
```

**Comment by jelalsultanov** [comment]
@makseq 

> ```
> "from_name": "tag",
> ```
> 
> =>
> 
> ```
> "from_name": "label",
> ```

Yeap Correct. I had same issue with this "tag" and "label". I just changed to "labels"
