### ISSUE TITLE
'task' not a key of responses when getting a project's tasks

### ISSUE THREAD

**Issue by w0ut0** [heartexlabs/label-studio-sdk#48]
After fetching a project, I want to get the project's tasks.

```python
project = ls_client.get_project(10)
task_ids = project.get_tasks()
```
In the SDK, this calls 
```python
response = self.make_request('GET', '/api/tasks', params)
```

However, this returns an array of tasks, so the following line fails:
```
#project.py:702
data = response.json()
tasks = data['tasks']
```

Switching the endpoint to `/api/dm/tasks` seems to work.

**Comment by makseq** [comment]
Please, update your LS instance to the latest master branch or downgrade SDK version. This api/dm/tasks is deprecated.
