### ISSUE TITLE
Bug in datamanager Column class

### ISSUE THREAD

**Issue by usamakh20** [heartexlabs/label-studio-sdk#50]
Hi, 
I have narrowed down an extra space on this [line](https://github.com/heartexlabs/label-studio-sdk/blob/62122e720c07f61662f3c665cc8e1da83496dfed/label_studio_sdk/data_manager.py#L203) that causes the filter to not be created when using this to create or update views.

**Comment by makseq** [comment]
Thank you very much for your report. [It's fixed now](https://github.com/heartexlabs/label-studio-sdk/blob/master/label_studio_sdk/data_manager.py#L203).
