### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by binit9** [heartexlabs/label-studio-sdk#53]
When I try to open a task in the UI I get this error - **TypeError: Cannot read properties of undefined (reading 'endsWith')**.

I have created project, imported/synced tasks and uploaded predictions (pre-annotation), but can't open a task to refine labeling. Could someone please help?

**Comment by makseq** [comment]
Please provide 
* screenshot with error
* uploaded task and predictions in json format

**Comment by binit9** [comment]
I am extremely sorry for the late response. This problem is resolved now. There was a minor issue in the prediction JSON format, which is fine now. You may close the issue.

**Comment by makseq** [comment]
Thanks for answering!
