### ISSUE TITLE
Pinned pydantic dependency version conflicts with other projects

### ISSUE THREAD

**Issue by xtrementl** [heartexlabs/label-studio-sdk#75]
I'm attempting to use `label-studio-sdk` with another dependency which depends on a slightly newer version of `pydantic`. However, since this project has an explicit version of `pydantic==1.8.2`, the two conflict.

Would it be possible to use `>= 1.8.2` in the `requirements.txt` to be more compatible?

Thanks!

**Comment by makseq** [comment]
Yes, it's possible, but we need to limit somehow, e.g. ~=1.8.0. It would be great if you could create a PR :-)
