### ISSUE TITLE
Add cookies to Client SDK

### ISSUE THREAD

**Issue by colby-vickerson** [heartexlabs/label-studio-sdk#76]
I need to pass cookies to the requests session setup in the Client class. The current functionality only supports headers when instantiating the Client class. Update functionality to also allow cookies to be passed into the requests session.

**Comment by colby-vickerson** [comment]
When creating the PR, I noticed that you can pass in a session to the Client: https://github.com/heartexlabs/label-studio-sdk/blob/d6ae9585fc068915a54cd6a6839669b7a4e3f599/label_studio_sdk/client.py#L32.

I think the cookies is a nice addition because you can take advantage of this method that sets up the session: https://github.com/heartexlabs/label-studio-sdk/blob/d6ae9585fc068915a54cd6a6839669b7a4e3f599/label_studio_sdk/client.py#L207

**Comment by makseq** [comment]
Merged to master.
