### ISSUE TITLE
pydantic version incompatible with label-studio

### ISSUE THREAD

**Issue by engma-linguistics** [heartexlabs/label-studio-sdk#98]
Presumably one would want label-studio and label-studio-sdk to both be able to be installed; their current versions pinned for pydantic are incompatible.

**Comment by ToJestKrzysio** [comment]
+1

**Comment by makseq** [comment]
Fixed in https://github.com/heartexlabs/label-studio/pull/3553

**Comment by engma-linguistics** [comment]
@makseq looks like the build failed. https://github.com/heartexlabs/label-studio/pull/3553#partial-pull-merging

**Comment by makseq** [comment]
@engma-linguistics it's github actions issue, waiting until they fix it..

**Comment by makseq** [comment]
docker build has been passed.
